
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      run: make test

    - name: Run coverage
      uses: codecov/codecov-action@v1

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
    - run: |
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        gcloud auth configure-docker

    - name: Push Image
      run: make push-image

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
    - run: gcloud run deploy messaging --image=gcr.io/messaging-trioptima/messaging --platform=managed --region=europe-north1 --concurrency=1 --port=8080 --timeout=4 --set-env-vars DB_ID=messaging,DB_TABLE=messages,GOOGLE_CLOUD_PROJECT=messaging-trioptima


